install:
	@pip install -r requirements.txt
	
run:
	@FLASK_APP=app.py FLASK_DEBUG=development flask run --host=0.0.0.0 --port=3000


clean:
	find . -name "__pycache__" -exec rm -r {} +  
	find . -name "*.pyc" -delete
